#!/bin/bash
# 🚀 QUICK START - Optimized Data Collection V6

echo "═══════════════════════════════════════════════════════════════════════════════"
echo "  📊 OPTIMIZED DATA COLLECTION - START GUIDE"
echo "═══════════════════════════════════════════════════════════════════════════════"
echo ""
echo "  ✅ Topology verified: h1-h20 (botnet), h60-h65 (clients)"
echo "  ✅ Capture interface: s6-eth1 (backbone, 99.7% pass rate)"
echo "  ✅ Filter updated: Bidirectional (REQUEST + RESPONSE)"
echo "  ✅ Collection order: ATTACK first (1-4), NORMAL last (0)"
echo ""
echo "═══════════════════════════════════════════════════════════════════════════════"
echo ""

echo "📋 QUICK START:"
echo ""
echo "  1️⃣  Open TERMINAL 1 - Packet Capture:"
echo ""
echo "      cd /home/tgf/Documents/DoAn_SDN/thuThapData"
echo "      sudo python3 batPack123.py"
echo ""
echo "  2️⃣  Open TERMINAL 2 - Flow Processing:"
echo ""
echo "      cd /home/tgf/Documents/DoAn_SDN/thuThapData"
echo "      sudo python3 auto_dataset_generator.py"
echo ""
echo "  3️⃣  TERMINAL 3 - Mininet CLI (paste commands below):"
echo ""
echo "      containernet> [Run commands from phases below]"
echo ""
echo "═══════════════════════════════════════════════════════════════════════════════"
echo ""

echo "⏱️  PHASES (Total: ~90 min)"
echo ""

echo "🔴 PHASE 1: UDP Flood (10 min)"
echo "   Mininet CMD:"
echo "   py [net.get(f'h{i}').cmd('pkill -f attack/ traffic/') for i in range(1, 21)] + [net.get(f'h{i}').cmd('pkill -f attack/ traffic/') for i in range(60, 66)]"
echo "   [Wait 2 seconds]"
echo "   py [net.get(f'h{i}').cmd('cd /home/tgf/Documents/DoAn_SDN && python3 attack/udp_flood.py 10.0.0.10 &') for i in range(1, 5)]"
echo "   Expected: ~80K samples in 10 min"
echo ""

echo "🔴 PHASE 2: SYN Flood (10 min)"
echo "   [Same kill command]"
echo "   py [net.get(f'h{i}').cmd('cd /home/tgf/Documents/DoAn_SDN && python3 attack/syn_flood.py 10.0.0.10 &') for i in range(6, 11)]"
echo "   Expected: ~160K cumulative samples"
echo ""

echo "🔴 PHASE 3: HTTP Flood (10 min)"
echo "   [Same kill command]"
echo "   py [net.get(f'h{i}').cmd('cd /home/tgf/Documents/DoAn_SDN && python3 attack/http_flood.py 10.0.0.10 &') for i in range(11, 15)]"
echo "   Expected: ~240K cumulative samples"
echo ""

echo "🔴 PHASE 4: Slowloris (10 min)"
echo "   [Same kill command]"
echo "   py [net.get(f'h{i}').cmd('cd /home/tgf/Documents/DoAn_SDN && python3 attack/slowloris.py 10.0.0.10 &') for i in range(16, 21)]"
echo "   Expected: ~320K cumulative samples"
echo ""

echo "🟢 PHASE 0: Normal Traffic (50 min)"
echo "   [Same kill command]"
echo "   py [net.get(f'h{i}').cmd('cd /home/tgf/Documents/DoAn_SDN && python3 traffic/normal.py http://10.0.0.10:8000 &') for i in range(60, 66)]"
echo "   Expected: ~400K cumulative samples ✅"
echo ""

echo "═══════════════════════════════════════════════════════════════════════════════"
echo ""
echo "📊 FINAL VALIDATION (after all phases):"
echo ""
echo "   wc -l master_dataset_v6.csv"
echo "   # Expected: 400001 (400K rows + 1 header)"
echo ""
echo "═══════════════════════════════════════════════════════════════════════════════"
echo ""
echo "📖 For detailed guide, read:"
echo "   DATA_COLLECTION_OPTIMIZED.md"
echo ""
echo "🤖 For full phase instructions with timings, run:"
echo "   python3 data_collection_orchestrator.py"
echo ""
