#!/bin/bash
#
# HƯỚNG DẪN CHẠY TOÀN BỘ PIPELINE AI V2
# Từ: Check Data → Training Colab → Deployment
#
# Mục lục:
# 1. Kiểm tra dữ liệu (Check Data)
# 2. Upload dữ liệu lên Colab
# 3. Training trên Colab
# 4. Download models
# 5. Triển khai (Deployment)
#

echo "=========================================="
echo "   AI V2 - FULL PIPELINE EXECUTION GUIDE"
echo "=========================================="
echo ""

# =========== PHASE 1: CHECK DATA ===========
echo "[1] KIỂM ĐỊNH DỮ LIỆU (Check Dataset)"
echo "========================================"
echo "Chạy lệnh này để kiểm tra dữ liệu thu thập được:"
echo ""
echo "  cd /home/tgf/Documents/DoAn_SDN/ai"
echo "  source ../sdn_env/bin/activate"
echo "  python check_data.py"
echo ""
echo "Output sẽ cho bạn biết:"
echo "  - Kiểu dữ liệu có đúng không (phải toàn số)"
echo "  - Dữ liệu sạch (NaN, Infinity)"
echo "  - Class weights để cân bằng"
echo "  - Phân bố đặc trưng"
echo "  - Outliers"
echo ""
echo "Nếu thấy 'READY 100%', bạn có thể tiếp tục bước 2"
echo ""

# =========== PHASE 2: UPLOAD DATA ===========
echo "[2] UPLOAD DỮ LIỆU LÊN GOOGLE DRIVE"
echo "===================================="
echo "Sau khi check_data.py báo OK, hãy:"
echo ""
echo "  2a. Mở Google Drive: https://drive.google.com"
echo "  2b. Upload file: /home/tgf/Documents/DoAn_SDN/thuThapData/master_dataset_v6.csv"
echo "  2c. Ghi nhớ đường dẫn file trên Drive (vd: /MyDrive/master_dataset_v6.csv)"
echo ""

# =========== PHASE 3: TRAINING ON COLAB ===========
echo "[3] TRAINING TRÊN GOOGLE COLAB"
echo "==============================="
echo ""
echo "Bước 3a: Mở Google Colab"
echo "  - Truy cập: https://colab.research.google.com"
echo "  - Tạo Notebook mới"
echo ""
echo "Bước 3b: Mount Google Drive trong Colab"
echo "  Chạy cell này:"
echo ""
echo "    from google.colab import drive"
echo "    drive.mount('/content/drive')"
echo ""
echo "Bước 3c: Clone Repository (hoặc upload files)"
echo "  Cách 1 - Clone (nếu bạn có repo):"
echo ""
echo "    !git clone https://github.com/your-repo/DoAn_SDN.git"
echo "    %cd DoAn_SDN"
echo ""
echo "  Cách 2 - Upload file train_colab_v2.py:"
echo "    - Upload files từ /home/tgf/Documents/DoAn_SDN/ai/"
echo "    - config_v2.py"
echo "    - train_colab_v2.py"
echo ""
echo "Bước 3d: Install dependencies"
echo "  Chạy cell này:"
echo ""
echo "    !pip install torch torchvision torchaudio"
echo "    !pip install pandas scikit-learn numpy matplotlib seaborn"
echo "    !pip install nfstream requests rich joblib"
echo ""
echo "Bước 3e: Thiết lập Google Drive path"
echo "  Chạy cell này:"
echo ""
echo "    import os"
echo "    os.chdir('/content/drive/MyDrive')  # Thay thế path của bạn"
echo ""
echo "Bước 3f: CHẠY TRAINING (cell chính)"
echo "  Chạy cell này (mất 3-5 ngày tùy GPU):"
echo ""
echo "    exec(open('train_colab_v2.py').read())"
echo ""
echo "Bước 3g: KỲNGHỈ SAU KHI TRAINING XONG"
echo "  Khi training xong, bạn sẽ thấy:"
echo "    ✅ Autoencoder training complete"
echo "    ✅ Classifier training complete"
echo "    ✅ Models saved successfully"
echo ""
echo "  Và 4 file sẽ được tạo:"
echo "    - sdn_scaler.pkl"
echo "    - sdn_autoencoder_contrastive.pth"
echo "    - sdn_model_parallel_fusion.pth"
echo "    - ae_threshold.pkl"
echo ""

# =========== PHASE 4: DOWNLOAD MODELS ===========
echo "[4] DOWNLOAD FILE MODELS TỪ COLAB"
echo "==================================="
echo ""
echo "Sau khi training xong:"
echo "  - Các file models sẽ được tạo trong Colab"
echo "  - Download chúng về máy local"
echo "  - Copy vào thư mục: /home/tgf/Documents/DoAn_SDN/ai/"
echo ""
echo "Kiểm tra xem các file đã có chưa:"
echo ""
echo "  ls -lah /home/tgf/Documents/DoAn_SDN/ai/sdn_*.pth"
echo "  ls -lah /home/tgf/Documents/DoAn_SDN/ai/sdn_scaler.pkl"
echo "  ls -lah /home/tgf/Documents/DoAn_SDN/ai/ae_threshold.pkl"
echo ""

# =========== PHASE 5: DEPLOYMENT ===========
echo "[5] TRIỂN KHAI HỆ THỐNG (DEPLOYMENT)"
echo "===================================="
echo ""
echo "Các bước triển khai:"
echo ""
echo "5a. Chuẩn bị môi trường:"
echo "  - Bắt đầu Mininet/Containernet:"
echo ""
echo "    sudo python /home/tgf/Documents/DoAn_SDN/topology/research_topo.py"
echo ""
echo "  - Start ONOS controller (nếu chưa có):"
echo ""
echo "    docker-compose up onos"
echo ""
echo "5b. Start Data Collection (Terminal 1):"
echo ""
echo "    cd /home/tgf/Documents/DoAn_SDN/thuThapData"
echo "    source ../sdn_env/bin/activate"
echo "    python batPack123.py"
echo ""
echo "5c. Start IDS Engine (Terminal 2):"
echo ""
echo "    cd /home/tgf/Documents/DoAn_SDN/ai"
echo "    source ../sdn_env/bin/activate"
echo "    python run_onos_v2.py"
echo ""
echo "5d. Monitor Logs (Terminal 3):"
echo ""
echo "    tail -f /home/tgf/Documents/DoAn_SDN/logs/ids_engine_v2.log"
echo ""
echo "5e. Inject Test Attack (Mininet Console):"
echo ""
echo "    containernet> h1 python /home/tgf/Documents/DoAn_SDN/attack/syn_flood.py"
echo ""
echo "5f. Verify Rules in ONOS:"
echo ""
echo "    curl -u onos:rocks http://127.0.0.1:8181/onos/v1/flows | python -m json.tool"
echo ""
echo ""

# =========== ENVIRONMENT VARIABLES ===========
echo "[6] ENVIRONMENT VARIABLES (TÙY CHỌN)"
echo "====================================="
echo ""
echo "Bạn có thể tuning các biến môi trường:"
echo ""
echo "  export AI_MODEL_PATH=/path/to/models"
echo "  export ONOS_URL=http://127.0.0.1:8181/onos/v1"
echo "  export ONOS_USER=onos"
echo "  export ONOS_PASS=rocks"
echo "  export EMA_ALPHA=0.05"
echo "  export COOLDOWN_TIME=300"
echo "  export MAX_IPS=1000"
echo ""

# =========== TROUBLESHOOTING ===========
echo "[7] TROUBLESHOOTING"
echo "==================="
echo ""
echo "❌ Lỗi: ModuleNotFoundError: No module named 'config_v2'"
echo "✅ Giải pháp: Chạy từ thư mục ai/"
echo "   cd /home/tgf/Documents/DoAn_SDN/ai"
echo "   python train_colab_v2.py"
echo ""
echo "❌ Lỗi: CUDA out of memory"
echo "✅ Giải pháp: Giảm BATCH_SIZE trong train_colab_v2.py"
echo "   BATCH_SIZE = 128  # thay vì 256"
echo ""
echo "❌ Lỗi: FIFO not created"
echo "✅ Giải pháp: Tạo FIFO thủ công"
echo "   mkfifo thuThapData/zeek_stream.json"
echo "   mkfifo thuThapData/zeek_stream_slowloris.json"
echo ""
echo "❌ Lỗi: ONOS connection refused"
echo "✅ Giải pháp: Kiểm tra ONOS đã chạy chưa"
echo "   curl -u onos:rocks http://127.0.0.1:8181/onos/v1/apps"
echo ""
echo "❌ Lỗi: Models not found when running IDS"
echo "✅ Giải pháp: Kiểm tra models đã được download chưa"
echo "   ls -la ai/sdn_*.pth"
echo ""

# =========== FINAL CHECKLIST ===========
echo "[8] CHECKLIST TRƯỚC KHI CHẠY"
echo "============================="
echo ""
echo "Đánh dấu khi đã hoàn thành:"
echo ""
echo "  [ ] Dataset được check_data.py báo 'READY 100%'"
echo "  [ ] File master_dataset_v6.csv được upload lên Drive"
echo "  [ ] Training xong trên Colab (4 model files được tạo)"
echo "  [ ] Model files được download và copy vào ai/"
echo "  [ ] Mininet/Containernet đang chạy"
echo "  [ ] ONOS controller đang chạy"
echo "  [ ] Virtual environment (sdn_env) được activate"
echo "  [ ] batPack123.py được start (data collection)"
echo "  [ ] run_onos_v2.py được start (IDS engine)"
echo ""

echo "=========================================="
echo "✅ HƯỚNG DẪN HOÀN THÀNH!"
echo "Bắt đầu từ bước 1, làm theo thứ tự!"
echo "=========================================="
echo ""
